INSERT INTO TIPO_FORMA_PAGAMENTO(TIPO, PAGAMENTO_ONLINE) values ('Dinheiro', FALSE);
INSERT INTO TIPO_FORMA_PAGAMENTO(TIPO, PAGAMENTO_ONLINE) values ('Cheque', FALSE);
INSERT INTO TIPO_FORMA_PAGAMENTO(TIPO, PAGAMENTO_ONLINE) values ('Máquina', FALSE);
INSERT INTO TIPO_FORMA_PAGAMENTO(TIPO, PAGAMENTO_ONLINE) values ('Cartão', TRUE);
