INSERT INTO RESTAURANTE(NOME, ID_FORMA_PAGAMENTO) values ('Churrascaria Farroupilha', 1);
INSERT INTO RESTAURANTE(NOME, ID_FORMA_PAGAMENTO) values ('Churrascaria Farroupilha', 2);
INSERT INTO RESTAURANTE(NOME, ID_FORMA_PAGAMENTO) values ('Churrascaria Farroupilha', 3);
INSERT INTO RESTAURANTE(NOME, ID_FORMA_PAGAMENTO) values ('Churrascaria Farroupilha', 4);

INSERT INTO RESTAURANTE(NOME, ID_FORMA_PAGAMENTO) values ('Minas Tchê', 1);