INSERT INTO RESTAURANTE_FORMA_PAGAMENTO(ID_RESTAURANTE, ID_FORMA_PAGAMENTO) values (1,1);
INSERT INTO RESTAURANTE_FORMA_PAGAMENTO(ID_RESTAURANTE, ID_FORMA_PAGAMENTO) values (1,2);
INSERT INTO RESTAURANTE_FORMA_PAGAMENTO(ID_RESTAURANTE, ID_FORMA_PAGAMENTO) values (1,3);
INSERT INTO RESTAURANTE_FORMA_PAGAMENTO(ID_RESTAURANTE, ID_FORMA_PAGAMENTO) values (1,4);

INSERT INTO RESTAURANTE_FORMA_PAGAMENTO(ID_RESTAURANTE, ID_FORMA_PAGAMENTO) values (2,1);