INSERT INTO USUARIO_FORMA_PAGAMENTO(ID_USUARIO, ID_FORMA_PAGAMENTO) values (1,1);
INSERT INTO USUARIO_FORMA_PAGAMENTO(ID_USUARIO, ID_FORMA_PAGAMENTO) values (1,2);
INSERT INTO USUARIO_FORMA_PAGAMENTO(ID_USUARIO, ID_FORMA_PAGAMENTO) values (1,3);
INSERT INTO USUARIO_FORMA_PAGAMENTO(ID_USUARIO, ID_FORMA_PAGAMENTO) values (1,4);

INSERT INTO USUARIO_FORMA_PAGAMENTO(ID_USUARIO, ID_FORMA_PAGAMENTO) values (2,1);